### ISSUE TITLE
linuxdvb_fake.c

### ISSUE THREAD

**Issue by kueken** [e2iplayer/exteplayer3#13]
Hello
Can it be that there is something wrong?
`writev_with_retry`
There have errors when compiling.
greetings

**Comment by e2iplayer** [comment]
Hello,

As you can read this is fake implementation, so what for you try to compile it?

I am using it for debug purpose when I compile exteplayer3 for PC (fake version),

**Comment by kueken** [comment]
Ah ok...

I understood it was a universal solution and had tried to test locally as a replacement.

Thank you
