### ISSUE TITLE
Problem with avi (xvid/divx)

### ISSUE THREAD

**Issue by kueken** [e2iplayer/exteplayer3#14]
Hallo (again;-))

I tested the last changes on sh4.
ffmpeg 4.1
mp4 / mkv without problems.
In the avi-Cotainer but it is currently not running around.

Maybe you would like to compare that with my Branch?
There are the updates from the libeplayer3 of the DDT included.
Unfortunately, I have too little idea to really cooperate.

greetings

**Comment by e2iplayer** [comment]
But what ffmpeg libraries are you use?

Try these ones:
http://www.e2iplayer.gitlab.io/precompiled/ffmpeg4.1/ffmpeg4.1_sh4_fpu_hard_openssl1.0.2_dash_librtmp_native_rtmp.tar.gz

Or if you have old libc then:
http://www.e2iplayer.gitlab.io/precompiled/ffmpeg4.1/ffmpeg4.1_sh4_old_fpu_hard_openssl1.0.2_dash_librtmp_native_rtmp.tar.gz

**Comment by kueken** [comment]
https://github.com/kueken/openpli-oe-core/tree/develop/meta-openpli/recipes-multimedia/ffmpeg

This is currently my ffmpeg solution with patching.

Patches are also derived from the DDT.

**Comment by e2iplayer** [comment]
You report issue here, so you should check this software.
If you have problem with different software than what for you report issue here?

**Comment by kueken** [comment]
Yes that is done, build me but just an image without the already installed ffmpeg.

It takes time.

greetings

**Comment by e2iplayer** [comment]
It is really easy to test:

```
cd /tmp
wget http://www.e2iplayer.gitlab.io/precompiled/ffmpeg4.1/ffmpeg4.1_sh4_fpu_hard_openssl1.0.2_dash_librtmp_native_rtmp.tar.gz
mkdir -p /iptvplayer_rootfs
tar -xvf ffmpeg4.1_sh4_fpu_hard_openssl1.0.2_dash_librtmp_native_rtmp.tar.gz -C /iptvplayer_rootfs
wget https://gitlab.com/www.e2iplayer/resources/blob/master/packages/bin/sh4/exteplayer3_fpu_hard_ffmpeg4.1
chmod 777 exteplayer3_fpu_hard_ffmpeg4.1
./exteplayer3_fpu_hard_ffmpeg4.1 /path/to/xvid/file.avi
```

So, what is hard for you?

**Comment by e2iplayer** [comment]
No you do not have to!

The only thing you need to do is:
```
cd /tmp
wget http://www.e2iplayer.gitlab.io/precompiled/ffmpeg4.1/ffmpeg4.1_sh4_fpu_hard_openssl1.0.2_dash_librtmp_native_rtmp.tar.gz
mkdir -p /iptvplayer_rootfs
tar -xvf ffmpeg4.1_sh4_fpu_hard_openssl1.0.2_dash_librtmp_native_rtmp.tar.gz -C /iptvplayer_rootfs
wget https://gitlab.com/www.e2iplayer/resources/blob/master/packages/bin/sh4/exteplayer3_fpu_hard_ffmpeg4.1
chmod 777 exteplayer3_fpu_hard_ffmpeg4.1
./exteplayer3_fpu_hard_ffmpeg4.1 /path/to/xvid/file.avi
```

and nothing more

**Comment by kueken** [comment]
I did that and unfortunately did not have any more output of the media files.
Flash me now an ATV and test it in your area.

**Comment by e2iplayer** [comment]
What? you put some files in location not used by your system and this affect your media playback files?

I do not think so. Really.

**Comment by kueken** [comment]
oh ..., I would have to build that again ...
I had already built before with 4.1 and used the exteplayer3 with it.
Everything had worked out perfectly.
Currently I could see the mentioned change. As I said only in the avi container.
That was always the strength of ffmpeg / exteplayer3.
So this was feedback on my part.
Thank you very much for your support

greetings

**Comment by e2iplayer** [comment]
Do you have sample file which works before last changes and does not work now?

**Comment by e2iplayer** [comment]
Could you please provide sample file?

**Comment by kueken** [comment]
Sorry for late reply ...
Had not seen it at all.
It is actually the same error with any stream in the avi container.
Somehow sh4 does not seem to get along with the debug-code.
Any divx / Xvid stream shows the phenomenon.
greetings

**Comment by e2iplayer** [comment]
I have one SH4 STB and I can not reproduce your problem.
This is why I am asking for sample.

**Comment by kueken** [comment]
I honestly tested everything through.
Debug and sh4 are not running smoothly. It falters.
No matter what avi file I try.
I upload a file as desired.
As I said error is with all avi files.
ffmpeg 4.1 is used.

**Comment by e2iplayer** [comment]
This file plays without problem for me on SH4 STB (nBox).

**Comment by kueken** [comment]
I feared it
You tested it with ffmpeg4.1?

Then I'll probably have to continue looking for the error.
Remains only something on my built ffmpeg.
Where the precompilte of you showed the same mistake with me.
There was still a bug in my driver sh4 (sti7105 / 7111).
Pity...
Thank you for watching

**Comment by e2iplayer** [comment]
Yes, I tested it on the exteplayer3 v55  ffmpeg 4.1

**Comment by e2iplayer** [comment]
> nbox:~# cat /proc/cpuinfo
> machine         : STb7100 Reference board
> processor       : 0
> cpu family      : sh4
> cpu variant     : sh4-202
> cpu type        : STx7100
> cut             : 3.x
> cpu flags       : fpu
> cache type      : split (harvard)
> icache size     : 16KiB (2-way)
> dcache size     : 32KiB (2-way)
> address sizes   : 29 bits physical
> bogomips        : 263.16
> nbox:~#

What is your exact problem? This file do not work at all? Black screen or what?

**Comment by kueken** [comment]
It is shown haltingly with picture and sound

**Comment by e2iplayer** [comment]
Please test this binary:
[exteplayer3.zip](https://github.com/e2iplayer/exteplayer3/files/2866477/exteplayer3.zip)

**Comment by kueken** [comment]
The version runs without error

**Comment by e2iplayer** [comment]
https://github.com/e2iplayer/exteplayer3/commit/727436f5b210aab7b1b1895159613c1d38f8a867

**Comment by kueken** [comment]
Have it rebuilt and now everything is running.

Many Thanks

greetings
