### ISSUE TITLE
exteplayer3 options ?

### ISSUE THREAD

**Issue by thawtes** [e2iplayer/exteplayer3#15]
hello,

[-t id]
[-9 id]
[-h headers]
[-u user-agent]
[-c cookies]
... etc.

How do I use exteplayer3 options parameters in enigma2 bouquet? (with serviceapp)

thanks

**Comment by e2iplayer** [comment]
You should ask serviceapp

**Comment by thawtes** [comment]
> 
> 
> Hello,
> 
> You are asking in wrong place. You should ask on serviceapp project.
> 
> Regards,
> Sam

Excuse me! thanks...
