### ISSUE TITLE
exteplayer3 issue on H9S openATV 6.2/6.3

### ISSUE THREAD

**Issue by ozone1864** [e2iplayer/exteplayer3#16]
Dear SamSamSam,
Using serviceapp I switched enigma2 playback system to exteplayer3. I have installed all ffmpeg libraries.
The problem is it's not reading most of internal subtitles of movies that have (.PGS format) on 6.2/6.3 and in the some movies where there is high bitrate there is a little bit of lag only on 6.3.
Is there anything I can do from my side for internal embedded subtitle issue or its a limitation ?
And one more thing when the movie is lagging I check ram consumption I see I have 30mb left from 1 GB.
Regards,

**Comment by e2iplayer** [comment]
Hello,

Generally I do not use serviceapp. I handle exteplayer3 directly.

1. Regarding your problem with "little bit of lag" - please make sure that you are using last drivers. 
Another thing is to enable RAM buffering in the exteplayer3 for example 15MB:
```
exteplayer3 -b 15 /hdd/path_to_your_movie.mp4
```
I do not know if there is option in the serviceapp to set RAM buffer for exteplayer3 but as I wrote you can check if this fix your problem using directly exteplayer3 from command line.
To be able to run exteplayer3 from cmd you need free video and audio decoders for example you can disconnect signal cable to disable live signal.

2. Regarding your second question
What is the format of these internal subtitles?

Please provide output of the following command:
```
ffmpeg -i /hdd/path_to_your_movie.mp4
```
Regards,
Sam

**Comment by ozone1864** [comment]
All movies in this time have embedded subtitles which are in PGS format for colors and styles...
It would be fascinating if you enhance the exteplayer3 to support them really soon. Since no player on enigma2 support them until now so it would be a great good move.
Second I will try uninstalling everything and installing e2iplayer which will install exteplayer3 and latest drivers to see if there is still lags. 
Note : The problem is that the video and audio becomes out-of-sync for a moment until video lags which it fixes the problem during the time of watching. 
Problem is not on all movies only on high bitrates ones. I will provide you with media info of one movie of plenty which are lagging.
System: latest OPENATV 6.3 - ZGemma H9S

**Comment by ozone1864** [comment]
**First movie**
General
Unique ID                                : 132302362892606456700601950454502976328 (0x6388821C11C72AD1808370780578EB48)
Complete name                            : **Fantastic.Beasts.The.Crimes.Of.Grindelwald.2018.1080p.BluRay.REMUX.AVC.Atmos-EPSiLON.mkv**
Format                                   : Matroska
Format version                           : Version 4
File size                                : 24.3 GiB
Duration                                 : 2 h 13 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 26.0 Mb/s
Movie name                               : Fantastic Beasts The Crimes Of Grindelwald (2018)
Encoded date                             : UTC 2019-03-01 05:49:49
Writing application                      : mkvmerge v30.1.0 ('Forever And More') 64-bit
Writing library                          : libebml v1.3.6 + libmatroska v1.4.9
IMDB                                     : tt4123430
TMDB                                     : movie/338952

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 2 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 2 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 2 h 13 min
Bit rate mode                            : Variable
Bit rate                                 : 21.9 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.441
Stream size                              : 20.5 GiB (84%)
Title                                    : MPEG-4 AVC Video / 21946 kbps / 1080p / 23.976 fps / 16:9 / High Profile 4.1
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio #1
ID                                       : 2
Format                                   : MLP FBA 16-ch
Format/Info                              : Meridian Lossless Packing FBA with 16-channel presentation
Commercial name                          : Dolby TrueHD with Dolby Atmos
Codec ID                                 : A_TRUEHD
Duration                                 : 2 h 13 min
Bit rate mode                            : Variable
Bit rate                                 : 3 457 kb/s
Maximum bit rate                         : 5 013 kb/s
Channel(s)                               : 8 channels
Channel layout                           : L R C LFE Ls Rs Lb Rb
Sampling rate                            : 48.0 kHz
Frame rate                               : 1 200.000 FPS (40 SPF)
Compression mode                         : Lossless
Stream size                              : 3.23 GiB (13%)
Title                                    : Dolby TrueHD/Atmos Audio / 7.1 / 48 kHz /  3457 kbps / 16-bit
Language                                 : English
Default                                  : Yes
Forced                                   : No
Number of dynamic objects                : 15
Bed channel count                        : 1 channel
Bed channel configuration                : LFE

Audio #2
ID                                       : 3
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 13 min
Bit rate mode                            : Constant
Bit rate                                 : 448 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 429 MiB (2%)
Title                                    : Compatibility Track / Dolby Digital Audio / 5.1-EX / 48 kHz / 448 kbps
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Text #1
ID                                       : 4
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 2 h 13 min
Bit rate                                 : 27.8 kb/s
Count of elements                        : 3012
Stream size                              : 26.6 MiB (0%)
Title                                    : SDH
Language                                 : English
Default                                  : No
Forced                                   : No

Text #2
ID                                       : 5
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 2 h 12 min
Bit rate                                 : 21.0 kb/s
Count of elements                        : 2504
Stream size                              : 20.0 MiB (0%)
Language                                 : French
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 6
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 2 h 12 min
Bit rate                                 : 22.6 kb/s
Count of elements                        : 2508
Stream size                              : 21.5 MiB (0%)
Title                                    : Brazilian
Language                                 : Portuguese
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 7
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 2 h 12 min
Bit rate                                 : 22.9 kb/s
Count of elements                        : 2496
Stream size                              : 21.8 MiB (0%)
Title                                    : Latin American
Language                                 : Spanish
Default                                  : No
Forced                                   : No

**Comment by ozone1864** [comment]
**Second Movie**
General
Unique ID                                : 247721839942120915158266940759104590578 (0xBA5D7DAE6566A805AE24C423B01892F2)
Complete name                            : **Inception.2010.Blu-ray.Remux.1080p.VC-1.DTS-HD.MA.5.1-HDRemuX.mkv**
Format                                   : Matroska
Format version                           : Version 2
File size                                : 29.0 GiB
Duration                                 : 2h 28mn
Overall bit rate mode                    : Variable
Overall bit rate                         : 28.1 Mbps
Encoded date                             : UTC 2011-10-10 08:26:59
Writing application                      : mkvmerge v5.0.0 ('Die Wahre Liebe') built on Sep 25 2011 20:33:49
Writing library                          : libebml v1.2.2 + libmatroska v1.3.0

Video
ID                                       : 1
Format                                   : VC-1
Format profile                           : Advanced@L3
Codec ID                                 : V_MS/VFW/FOURCC / WVC1
Codec ID/Hint                            : Microsoft
Duration                                 : 2h 28mn
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : DTS
Format/Info                              : Digital Theater Systems
Format profile                           : MA / Core
Mode                                     : 16
Format settings, Endianness              : Big
Codec ID                                 : A_DTS
Duration                                 : 2h 28mn
Bit rate mode                            : Variable
Bit rate                                 : Unknown / 1 509 Kbps
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Compression mode                         : Lossless / Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text #1
ID                                       : 3
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Language                                 : English
Default                                  : Yes
Forced                                   : No

**Comment by e2iplayer** [comment]
PGS - Presentation Grapic Stream Subtitle Format
exteplayer3 at now supports only TEXT subtitles.

the second thing I asked you to make simple test:
```
exteplayer3 -b 15 /hdd/path_to_your_movie.mp4
```

So, simple perform this test.

**Comment by ozone1864** [comment]
I'll do the test when I get back home after some hours and give you feedback.
Thank you SamSamSam

**Comment by ozone1864** [comment]
**root@zgemmah9s:~#** exteplayer3 -b 15 /media/hdd/Series/Supernatural\ S13/Supernatural.S13E23.Let.the.Good.Times.Roll.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.
{"EPLAYER3_EXTENDED":{"version":62}}
file: [file:///media/hdd/Series/Supernatural S13/Supernatural.S13E23.Let.the.Good.Times.Roll.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.]
{"PLAYBACK_OPEN":{"OutputName":"Output", "file":"file:///media/hdd/Series/Supernatural S13/Supernatural.S13E23.Let.the.Good.Times.Roll.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON.", "sts":-1}}

**Comment by ozone1864** [comment]
Same  problem unnoticeable difference

**Comment by e2iplayer** [comment]
So, this must be the problem with drivers.

**Comment by ozone1864** [comment]
I will upload tomorrow a sample but there is something you should know.
Using the original player there are much less frame drops but I can't switch to original player
since exteplayer3 is the only player which supports resume playback and saving movie progress in the
Enhanced Movie Center (EMC).

**Comment by e2iplayer** [comment]
Original you mean hisiliconservice or serviceMP3?
If you are talking about hisilicon service then this does not prove anything since this player does not use video0, audio0 interfaces.

If you need to know more please read:
https://github.com/zgemma-star/meta-zgemma/issues/7

**Comment by ozone1864** [comment]
I know understand after I read your request to meta-zgemma. I think you should open your request ticket again after my issue is submitted.
What do you mean by hisilicon service ? The original player or I should download it ?
In serviceapp there is a player called "Original Player" maybe this one is hisilicon service or not ?
Can you elaborate more so that I can test and maybe we can report driver issue to zgemma

**Comment by e2iplayer** [comment]
I think you must read more.
