### ISSUE TITLE
PNG Plugin for exteplayer3

### ISSUE THREAD

**Issue by ozone1864** [e2iplayer/exteplayer3#17]
Dear SamSamSam,
I have installed the latest exteplayer3 on openATV 6.2 and the png plugin for PGS subtitles. No options regarding PGS subtitles are found in serviceapp after doing the symbolic link and neither for subtitle detection while playing movie. Maybe its problem with serviceapp. 
I did the test on mkv file in terminal and went success detecting PGS subtitles. 
Can you elaborate ?
Regards,

**Comment by e2iplayer** [comment]
Hello,

This is question to serviceapp not to me.
As you know I am handling exteplayer3 directly from python code (plugin E2iPlayer) without serviceapp.

https://forums.openpli.org/topic/68209-exteplayer3-support-for-the-embedded-pgs-presentation-graphic-stream-subtitle-format/

Regards,
Sam
